var pairs =
{
"data_management_ref_card_2023.3.0.0.pdf":{"2023":1}
,"2023":{"commure":1}
,"commure":{"data":1,"reviewing":1,"viewing":1,"system":1,"representative":1}
,"data":{"management":1,"integrations":1,"column":1,"overwrite":1,"2023":1,"radiology":1}
,"management":{"application":1}
,"application":{"quick":1,"helps":1,"analysts":1,"click":1}
,"quick":{"reference":1,"synopsis":1}
,"reference":{"data":1}
,"helps":{"application":1}
,"analysts":{"integration":1}
,"integration":{"engineers":1}
,"engineers":{"monitor":1}
,"monitor":{"data":1}
,"integrations":{"systems":1}
,"systems":{"investigate":1,"example":1}
,"investigate":{"resolve":1,"issue":1}
,"resolve":{"errors":1,"error":1}
,"errors":{"occur":1,"error":1,"currently":1,"option":1,"listed":1,"table":1,"possibly":1}
,"occur":{"during":1}
,"during":{"processing":1}
,"processing":{"interface":1,"message":1,"reprocessed":1}
,"interface":{"messages":1,"errors":1,"time":1,"message":1,"radiology":1}
,"messages":{"getting":1,"error":1,"issue":1,"sent":1,"current":1,"messages":1,"screen":1,"including":1,"processed":1,"once":1,"clicking":1}
,"getting":{"around":1}
,"around":{"using":1}
,"using":{"filters":1}
,"filters":{"screen":1,"narrow":1,"button":1,"report":1,"give":1}
,"screen":{"filters":1,"click":1,"select":1,"lists":1,"transactions":1,"filtering":1,"display":1}
,"narrow":{"results":1}
,"results":{"shown":1}
,"shown":{"screen":1}
,"click":{"filters":1,"add":1,"apply":1,"save":1,"gears":1,"icon":1,"heading":1,"select":1,"menu":1,"link":1,"bulk":1,"reprocess":1,"ignore":1,"message":1,"create":1,"edit":1}
,"button":{"pop":1,"click":1,"specific":1,"2023":1,"appears":1}
,"pop":{"filter":1}
,"filter":{"option":1,"save":1,"combinations":1,"name":1,"drop-down":1,"select":1}
,"option":{"select":1,"investigate":1,"specify":1,"add":1}
,"select":{"first":1,"filter":1,"open":1,"individual":1,"messages":1,"matches":1}
,"first":{"criteria":1}
,"criteria":{"example":1,"sure":1}
,"example":{"patient":1,"code":1,"map":1,"interface":1,"specify":1}
,"patient":{"mrn":1,"interface":1}
,"mrn":{"contains":1}
,"contains":{"123456554":1}
,"123456554":{"text":1}
,"text":{"enter":1,"grouped":1,"unresolved":1,"column":1}
,"enter":{"value":1,"mappings":1,"multiple":1}
,"value":{"field":1,"rad-sys-b":1}
,"field":{"applied":1}
,"applied":{"case":1}
,"case":{"sensitive":1}
,"sensitive":{"manner":1}
,"manner":{"click":1}
,"add":{"remove":1,"several":1,"new":1}
,"remove":{"additional":1}
,"additional":{"criteria":1}
,"sure":{"operator":1}
,"operator":{"correct":1}
,"correct":{"multiple":1}
,"multiple":{"operators":1,"entries":1}
,"operators":{"match":1}
,"match":{"ands":1}
,"ands":{"ors":1}
,"ors":{"click":1}
,"apply":{"apply":1,"filters":1}
,"report":{"saving":1,"report":1,"work":1,"number":1,"caution":1}
,"saving":{"filter":1}
,"save":{"frequently":1,"filters":1,"added":1}
,"frequently":{"used":1}
,"used":{"filter":1}
,"combinations":{"later":1}
,"later":{"click":1,"time":1}
,"give":{"filter":1}
,"name":{"save":1,"column":1}
,"added":{"filter":1}
,"drop-down":{"later":1,"gears":1}
,"time":{"click":1,"frame":1}
,"gears":{"icon":1}
,"icon":{"modify":1,"becomes":1,"double-click":1}
,"modify":{"delete":1,"system":1}
,"delete":{"saved":1,"mapping":1}
,"saved":{"filter":1}
,"becomes":{"enabled":1}
,"enabled":{"close":1}
,"close":{"sidebar":1}
,"sidebar":{"click":1,"lists":1}
,"double-click":{"blue":1}
,"blue":{"vertical":1,"header":1}
,"vertical":{"bar":1}
,"bar":{"click":1,"dmarc202330010032023":1}
,"heading":{"sort":1}
,"sort":{"rows":1}
,"rows":{"data":1}
,"column":{"sidebar":1,"view":1}
,"lists":{"available":1,"interface":1,"attempt":1}
,"available":{"menu":1}
,"menu":{"options":1,"icon":1,"option":1}
,"options":{"application":1}
,"open":{"sidebar":1}
,"dmarc202330010032023":{"2023":1}
,"reviewing":{"errors":1}
,"error":{"summary":1,"text":1,"removed":1,"individual":1,"reprocess":1,"error":1,"safely":1,"ignored":1}
,"summary":{"gives":1,"report":1}
,"gives":{"quick":1}
,"synopsis":{"interface":1}
,"currently":{"unresolved":1}
,"unresolved":{"errors":1,"click":1,"displayed":1}
,"grouped":{"together":1}
,"together":{"listed":1}
,"listed":{"single":1,"errors":1,"system":1}
,"single":{"row":1}
,"row":{"report":1}
,"work":{"list":1}
,"list":{"resolve":1}
,"removed":{"report":1}
,"number":{"errors":1,"system":1}
,"link":{"error":1,"name":1}
,"view":{"full":1,"details":1}
,"full":{"details":1}
,"details":{"error":1,"interface":1,"system":1}
,"individual":{"interface":1,"message":1}
,"displayed":{"bottom":1}
,"bottom":{"example":1,"screen":1}
,"code":{"img181":1,"mappings":1,"sets":1,"updating":1,"enter":1,"example":1,"img3":1,"gmandible":1,"mapping":1,"target":1,"fields":1,"search":1,"codes":1}
,"img181":{"rad-":1,"updating":1}
,"rad-":{"sys-a":1}
,"sys-a":{"mapped":1}
,"mapped":{"value":1,"interfacing":1,"test":1,"click":1}
,"rad-sys-b":{"interface":1}
,"issue":{"resolving":1,"reported":1}
,"resolving":{"error":1}
,"reprocess":{"interface":1,"click":1,"button":1,"message":1,"several":1}
,"sent":{"receiving":1}
,"receiving":{"system":1}
,"system":{"example":1,"mappings":1,"radiology":1,"need":1,"mapping":1,"mapped":1,"many-to-one":1,"number":1}
,"map":{"code":1}
,"updating":{"system":1}
,"mappings":{"code":1,"back":1,"option":1,"various":1,"once":1,"actual":1,"required":1}
,"back":{"screen":1}
,"message":{"want":1,"removes":1,"reprocessing":1,"view":1,"review":1,"recent":1,"errors":1,"usually":1,"failed":1,"side":1,"button":1,"processed":1}
,"want":{"reprocess":1}
,"bulk":{"edit":1}
,"edit":{"check":1,"delete":1,"modify":1}
,"check":{"box":1,"boxes":1}
,"box":{"blue":1}
,"header":{"select":1}
,"current":{"page":1}
,"page":{"click":1}
,"ignore":{"error":1}
,"safely":{"ignored":1}
,"ignored":{"changes":1,"message":1}
,"changes":{"status":1}
,"status":{"error":1}
,"removes":{"error":1}
,"caution":{"please":1}
,"please":{"care":1}
,"care":{"determining":1}
,"determining":{"whether":1}
,"whether":{"reprocess":1}
,"reprocessing":{"runs":1}
,"runs":{"risk":1}
,"risk":{"sending":1}
,"sending":{"older":1}
,"older":{"version":1}
,"version":{"data":1}
,"overwrite":{"newer":1}
,"newer":{"version":1}
,"viewing":{"messages":1}
,"including":{"without":1}
,"without":{"errors":1}
,"reported":{"interface":1}
,"processed":{"particular":1,"again":1}
,"particular":{"patient":1}
,"frame":{"click":1}
,"review":{"full":1}
,"recent":{"attempt":1}
,"attempt":{"processing":1}
,"table":{"bottom":1,"lists":1}
,"transactions":{"table":1}
,"usually":{"message":1}
,"failed":{"processing":1}
,"reprocessed":{"may":1}
,"may":{"displays":1}
,"displays":{"original":1}
,"original":{"transformed":1}
,"transformed":{"message":1}
,"side":{"side":1,"comparison":1}
,"comparison":{"once":1}
,"once":{"addressed":1,"messages":1,"created":1,"system":1}
,"addressed":{"errors":1}
,"possibly":{"updating":1}
,"specific":{"message":1}
,"again":{"reprocess":1}
,"several":{"messages":1,"system":1}
,"filtering":{"screen":1}
,"display":{"desired":1}
,"desired":{"messages":1}
,"clicking":{"check":1,"reprocess":1}
,"boxes":{"select":1}
,"specify":{"code":1,"test":1}
,"sets":{"need":1,"test":1}
,"need":{"mapped":1,"add":1}
,"interfacing":{"systems":1}
,"radiology":{"system":1,"data":1}
,"various":{"code":1}
,"test":{"codes":1,"code":1}
,"codes":{"result":1,"click":1,"code":1,"interface":1,"menu":1,"test":1,"already":1}
,"result":{"codes":1}
,"create":{"create":1,"new":1,"button":1}
,"new":{"system":1,"code":1,"codes":1}
,"mapping":{"code":1,"enter":1,"test":1,"created":1,"screen":1,"click":1,"source":1}
,"created":{"system":1,"listed":1}
,"actual":{"codes":1}
,"img3":{"radiology":1,"gmandible":1}
,"gmandible":{"radiology":1,"img4":1,"system":1}
,"many-to-one":{"mapping":1}
,"entries":{"example":1}
,"img4":{"gmandible":1}
,"required":{"depend":1}
,"depend":{"types":1}
,"types":{"interfaces":1}
,"interfaces":{"consult":1}
,"consult":{"commure":1}
,"representative":{"setting":1}
,"setting":{"system":1}
,"source":{"code":1}
,"target":{"code":1}
,"fields":{"type":1}
,"type":{"few":1}
,"few":{"characters":1}
,"characters":{"code":1}
,"search":{"select":1}
,"matches":{"found":1}
,"found":{"create":1}
,"appears":{"click":1}
,"already":{"mapped":1}
}
;Search.control.loadWordPairs(pairs);
