var pairs =
{
"adding":{"code":1,"new":1}
,"code":{"mapping":1,"mappings":1,"enter":1,"used":1,"search":1,"exist":1,"fly":1,"drawer":1,"click":1,"resides":1,"equivalent":1,"target":1,"just":1,"field":1,"available":1}
,"option":{"adding":1}
,"new":{"code":1}
,"mapping":{"accessed":1,"option":1,"sidebar":1,"want":1,"click":1,"drawer":1}
,"accessed":{"via":1}
,"via":{"system":1}
,"system":{"mapping":1,"mappings":1,"select":1,"code":1,"source":1}
,"select":{"system":1,"results":1}
,"sidebar":{"left":1}
,"identify":{"system":1}
,"want":{"add":1}
,"add":{"code":1}
,"click":{"link":1,"create":1,"field":1,"save":1}
,"link":{"name":1}
,"name":{"column":1}
,"mappings":{"details":1,"already":1,"table":1}
,"details":{"screen":1}
,"screen":{"opens":1}
,"opens":{"code":1,"complete":1}
,"already":{"exist":1}
,"exist":{"listed":1,"data":1,"source":1}
,"listed":{"code":1}
,"table":{"bottom":1,"create":1}
,"bottom":{"screen":1}
,"create":{"located":1,"new":1,"code":1,"button":1,"create":1}
,"located":{"top":1}
,"top":{"right":1}
,"right":{"code":1,"enter":1}
,"drawer":{"right":1,"opens":1}
,"enter":{"following":1,"code":1,"description":1,"target":1}
,"following":{"information":1}
,"source":{"code":1,"system.you":1,"codes":1,"system":1}
,"used":{"source":1}
,"system.you":{"click":1}
,"field":{"view":1,"click":1,"behaves":1,"methods":1}
,"view":{"full":1}
,"full":{"list":1}
,"list":{"source":1}
,"codes":{"currently":1}
,"currently":{"exist":1}
,"data":{"management":1}
,"management":{"application":1}
,"application":{"type":1,"create":1}
,"type":{"few":1}
,"few":{"characters":1}
,"characters":{"code":1}
,"search":{"select":1}
,"results":{"list":1}
,"button":{"display":1}
,"display":{"below":1}
,"below":{"field":1,"new":1}
,"fly":{"create":1}
,"complete":{"fields":1}
,"fields":{"below":1}
,"resides":{"example":1}
,"example":{"code":1}
,"description":{"enter":1,"code":1}
,"target":{"code":1,"system":1}
,"equivalent":{"code":1}
,"just":{"entered":1}
,"entered":{"above":1}
,"above":{"field":1}
,"behaves":{"similar":1}
,"similar":{"manner":1}
,"manner":{"source":1}
,"methods":{"selecting":1}
,"selecting":{"creating":1}
,"creating":{"new":1}
}
;Search.control.loadWordPairs(pairs);
