var pairs =
{
"error":{"descriptions":1,"categories":1,"messages":1,"statuses":1,"category":1,"happened":1,"severity":1}
,"following":{"table":1,"location":1}
,"table":{"describes":1}
,"describes":{"error":1}
,"categories":{"error":1}
,"messages":{"encounter":1}
,"encounter":{"data":1}
,"data":{"management":1,"integration":1}
,"management":{"application":1}
,"application":{"severity":1}
,"severity":{"levels":1,"level":1,"critical":1}
,"levels":{"described":1}
,"described":{"error":1}
,"statuses":{"severity":1}
,"sample":{"error":1}
,"level":{"explanation":1}
,"code":{"lookup":1,"code":1,"field":1,"source":1,"target":1,"mapping":1,"correct":1,"system":1,"equivalencies":1}
,"lookup":{"match":1}
,"matching":{"code":1}
,"field":{"name":1,"warning":1,"failure":1}
,"name":{"found":1}
,"found":{"system":1}
,"system":{"name":1,"mapped":1,"new":1,"obr-4":1}
,"warning":{"failure":1,"required":1}
,"non-required":{"field":1}
,"required":{"field":1}
,"failure":{"code":1}
,"source":{"system":1,"code":1}
,"mapped":{"code":1}
,"target":{"system":1,"code":1}
,"new":{"code":1}
,"mapping":{"added":1}
,"added":{"map":1}
,"map":{"source":1}
,"correct":{"target":1}
,"destination":{"unreachable":1,"may":1,"address":1}
,"processing":{"complete":1,"message":1}
,"complete":{"destination":1,"transporter":1}
,"message":{"complete":1,"destination":1,"received":1,"structural":1,"may":1}
,"transporter":{"cannot":1,"server":1}
,"cannot":{"send":1,"processed":1}
,"send":{"message":1}
,"may":{"due":1,"actual":1,"deficiency":1}
,"due":{"simple":1}
,"simple":{"network":1}
,"network":{"outage":1}
,"outage":{"occur":1}
,"occur":{"destination":1}
,"address":{"incorrect":1}
,"incorrect":{"requires":1}
,"requires":{"intervention":1}
,"intervention":{"commure":1}
,"commure":{"support":1}
,"invalid":{"message":1}
,"received":{"following":1,"obr-4":1,"expected":1}
,"location":{"location":1,"name":1}
,"multiple":{"repetition":1}
,"repetition":{"received":1,"obr-4":1}
,"obr-4":{"segment":1}
,"segment":{"repetition":1,"permitted":1,"received":1,"message":1}
,"obr":{"segment":1}
,"expected":{"obr":1}
,"pid":{"segment":1}
,"pv1":{"segment":1}
,"missing":{"code":1,"mrn":1,"identifier":1,"value":1}
,"mrn":{"pid-3":1}
,"pid-3":{"segment":1}
,"identifier":{"pid-18":1}
,"value":{"obx-8":1}
,"obx-8":{"segment":1}
,"structural":{"problem":1}
,"problem":{"match":1,"transporter":1}
,"match":{"interface":1}
,"interface":{"specifications":1}
,"specifications":{"cannot":1,"data":1}
,"note":{"errors":1}
,"errors":{"category":1}
,"category":{"vary":1}
,"vary":{"client":1}
,"client":{"based":1}
,"based":{"specifications":1}
,"transform":{"error":1,"experienced":1}
,"experienced":{"unexpected":1}
,"unexpected":{"error":1}
,"bug":{"transformation":1,"may":1}
,"transformation":{"message":1,"specifications":1}
,"actual":{"bug":1}
,"deficiency":{"transformation":1}
,"happened":{"please":1}
,"please":{"contact":1}
,"contact":{"commure":1}
,"critical":{"undefined":1,"problem":1}
,"server":{"storing":1}
,"storing":{"code":1}
,"equivalencies":{"depending":1}
,"depending":{"nature":1}
,"nature":{"issue":1}
,"issue":{"error":1}
,"undefined":{"requires":1}
,"posting":{"graphql":1}
,"graphql":{"throws":1}
,"throws":{"http":1}
,"http":{"500":1}
,"500":{"error":1}
,"pod":{"continuously":1}
,"continuously":{"crashing":1}
,"crashing":{"loop":1}
}
;Search.control.loadWordPairs(pairs);
