var pairs =
{
"applying":{"saved":1}
,"saved":{"filter":1}
,"previously":{"saved":1}
,"filter":{"sets":1,"drop-down":1,"click":1,"want":1,"applied":1}
,"sets":{"current":1,"personal":1,"created":1}
,"current":{"screen":1}
,"screen":{"listed":1,"choose":1,"filtered":1}
,"listed":{"filter":1}
,"drop-down":{"filter":1,"located":1}
,"personal":{"meaning":1}
,"meaning":{"filter":1}
,"created":{"saving":1}
,"saving":{"filter":1}
,"apply":{"filter":1}
,"click":{"filter":1,"clear":1}
,"located":{"bottom":1}
,"bottom":{"left":1}
,"left":{"screen":1}
,"choose":{"filter":1}
,"want":{"data":1}
,"data":{"screen":1}
,"filtered":{"based":1}
,"based":{"criteria":1}
,"criteria":{"defined":1}
,"defined":{"filter":1}
,"clear":{"filter":1}
,"applied":{"click":1}
}
;Search.control.loadWordPairs(pairs);
