var pairs =
{
"reprocessing":{"messages":1,"errors":1}
,"messages":{"messages":1,"option":1,"slide-out":1,"click":1,"current":1}
,"select":{"messages":1}
,"slide-out":{"menu":1}
,"menu":{"drawer":1}
,"find":{"message":1}
,"message":{"want":1,"link":1,"review":1,"details":1,"finished":1}
,"want":{"reprocess":1}
,"reprocess":{"either":1,"located":1,"message":1}
,"either":{"scrolling":1}
,"scrolling":{"list":1}
,"list":{"using":1}
,"using":{"filter":1}
,"filter":{"option":1}
,"option":{"filtering":1}
,"filtering":{"data":1}
,"data":{"screen":1}
,"click":{"check":1,"reprocess":1,"bulk":1,"message":1}
,"check":{"box":1}
,"box":{"next":1,"table\u2019s":1}
,"next":{"specific":1}
,"specific":{"messages":1,"message":1}
,"located":{"top":1}
,"top":{"left":1}
,"left":{"table":1}
,"bulk":{"edit":1}
,"edit":{"check":1}
,"table\u2019s":{"heading":1}
,"heading":{"area":1}
,"area":{"select":1,"bottom":1}
,"current":{"page":1}
,"page":{"click":1,"reprocessed":1}
,"note":{"messages":1}
,"reprocessed":{"example":1}
,"example":{"pagination":1}
,"pagination":{"area":1}
,"bottom":{"screen":1}
,"screen":{"indicates":1,"click":1}
,"indicates":{"rows":1}
,"rows":{"currently":1,"1-10":1}
,"currently":{"displayed":1}
,"displayed":{"rows":1}
,"1-10":{"reprocessed":1}
,"link":{"specific":1}
,"review":{"details":1}
,"details":{"message":1,"screen":1}
,"view":{"message":1}
,"finished":{"reprocessing":1}
,"errors":{"table":1,"latest":1,"longer":1}
,"table":{"show":1}
,"show":{"errors":1}
,"latest":{"processing":1}
,"processing":{"prior":1}
,"prior":{"errors":1}
,"longer":{"display":1}
}
;Search.control.loadWordPairs(pairs);
