var pairs =
{
"using":{"help":1}
,"help":{"system":1}
,"click":{"button":1,"thumbs":1,"buttons":1}
,"button":{"open":1,"return":1}
,"open":{"close":1}
,"close":{"table":1}
,"table":{"contents":1}
,"type":{"word":1}
,"word":{"phrase":1}
,"phrase":{"search":1,"return":1,"example":1}
,"search":{"field":1,"item":1,"specific":1,"result":1}
,"field":{"search":1}
,"item":{"help":1,"quotes":1}
,"system":{"drop-down":1}
,"drop-down":{"filter":1}
,"filter":{"left":1}
,"left":{"field":1}
,"specific":{"books":1}
,"books":{"item":1}
,"quotes":{"around":1}
,"around":{"phrase":1}
,"return":{"results":1,"home":1}
,"results":{"include":1}
,"include":{"words":1,"three":1}
,"words":{"phrase":1,"although":1}
,"example":{"clinical":1}
,"clinical":{"notes":1}
,"notes":{"detail":1}
,"detail":{"returns":1}
,"returns":{"results":1}
,"three":{"words":1}
,"although":{"necessarily":1}
,"necessarily":{"adjacent":1}
,"thumbs":{"indicate":1,"down":1}
,"indicate":{"topic":1,"found":1}
,"topic":{"useful":1}
,"useful":{"search":1}
,"result":{"successful":1}
,"successful":{"click":1}
,"down":{"indicate":1}
,"found":{"looking":1}
,"buttons":{"next":1}
,"next":{"previous":1}
,"previous":{"sequential":1}
,"sequential":{"topic":1}
,"home":{"page":1}
}
;Search.control.loadWordPairs(pairs);
