var pairs =
{
"data":{"retention":1,"management":1,"retain":1}
,"last":{"days":1}
,"days":{"worth":1,"old":1}
,"worth":{"interface":1,"data":1}
,"interface":{"messages":1}
,"messages":{"typically":1,"greater":1,"per":1}
,"typically":{"retained":1}
,"retained":{"data":1}
,"management":{"application":1}
,"application":{"messages":1}
,"greater":{"days":1}
,"old":{"automatically":1}
,"automatically":{"purged":1}
,"purged":{"integration":1}
,"integration":{"engine":1}
,"engine":{"based":1}
,"based":{"expected":1}
,"expected":{"volume":1}
,"volume":{"10,000":1,"number":1}
,"10,000":{"messages":1}
,"per":{"day":1}
,"day":{"organization":1}
,"organization":{"anticipates":1}
,"anticipates":{"higher":1}
,"higher":{"lower":1}
,"lower":{"volume":1}
,"number":{"days":1}
,"retain":{"adjusted":1}
,"adjusted":{"contact":1}
,"contact":{"commure":1}
,"commure":{"representative":1}
}
;Search.control.loadWordPairs(pairs);
