var pairs =
{
"viewing":{"message":1}
,"message":{"details":1,"want":1,"column":1,"message":1,"originated":1,"sent":1,"statuses":1,"date":1,"originally":1,"fails":1,"last":1,"errors":1,"failed":1,"updated":1,"processed":1,"successful":1,"transaction":1,"full":1,"transformed":1}
,"view":{"details":1,"click":1}
,"details":{"specific":1,"screen":1}
,"specific":{"message":1}
,"select":{"messages":1}
,"messages":{"sidebar":1,"failed":1}
,"sidebar":{"left":1}
,"identify":{"message":1}
,"want":{"view":1}
,"click":{"link":1,"transaction":1}
,"link":{"message":1,"following":1}
,"screen":{"opens":1,"following":1,"tabs":1,"table":1,"added":1}
,"opens":{"displays":1}
,"displays":{"information":1}
,"information":{"particular":1,"displayed":1,"error":1,"second":1,"transaction":1,"may":1}
,"particular":{"message":1}
,"top":{"screen":1}
,"following":{"information":1}
,"source":{"system":1}
,"system":{"message":1,"information":1}
,"target":{"system":1}
,"sent":{"intended":1}
,"intended":{"sent":1}
,"status":{"message":1,"error":1}
,"statuses":{"definitions":1,"severity":1}
,"definitions":{"statuses":1,"status":1,"severity":1}
,"received":{"date":1,"first":1}
,"date":{"message":1,"last":1,"time":1}
,"originally":{"received":1}
,"first":{"attempt":1,"time":1}
,"attempt":{"processing":1,"transaction":1}
,"processing":{"occurred":1,"multiple":1,"done":1,"message":1,"due":1,"errors":1,"depending":1}
,"occurred":{"message":1}
,"fails":{"processing":1}
,"multiple":{"attempts":1}
,"attempts":{"process":1,"processing":1,"transactions":1}
,"process":{"attempt":1,"times":1}
,"last":{"processed":1,"time":1,"transaction":1}
,"processed":{"date":1,"successfully":1}
,"time":{"processing":1,"transactions":1,"message":1}
,"done":{"message":1}
,"transaction":{"message":1,"click":1,"link":1}
,"patient":{"name":1,"mrn":1}
,"name":{"message":1}
,"mrn":{"message":1}
,"bottom":{"screen":1}
,"tabs":{"two":1}
,"two":{"tables":1}
,"tables":{"errors":1}
,"errors":{"transactions":1,"table":1,"errors":1,"listed":1,"latest":1}
,"table":{"interface":1,"bottom":1,"includes":1,"shows":1,"message":1,"blank":1,"display":1,"table":1,"contains":1}
,"interface":{"message":1}
,"listed":{"errors":1,"table":1}
,"includes":{"following":1}
,"error":{"category":1,"error":1,"descriptions":1,"categories":1,"text":1,"limited":1,"statuses":1,"displayed":1,"caused":1}
,"category":{"error":1}
,"descriptions":{"list":1}
,"list":{"error":1}
,"text":{"describing":1,"original":1,"message":1}
,"describing":{"error":1}
,"limited":{"detail":1}
,"severity":{"levels":1,"error":1}
,"levels":{"definitions":1}
,"please":{"note":1}
,"note":{"errors":1}
,"shows":{"errors":1,"transactions":1}
,"latest":{"attempt":1}
,"failed":{"processing":1,"process":1}
,"due":{"matching":1}
,"matching":{"code":1}
,"code":{"error":1,"mapping":1}
,"displayed":{"errors":1}
,"added":{"new":1}
,"new":{"code":1,"errors":1}
,"mapping":{"correct":1}
,"correct":{"issue":1}
,"issue":{"reprocessed":1}
,"reprocessed":{"interface":1}
,"updated":{"show":1}
,"show":{"information":1}
,"second":{"processing":1}
,"successfully":{"without":1}
,"without":{"errors":1}
,"display":{"new":1}
,"transactions":{"table":1,"attempts":1,"listed":1}
,"successful":{"first":1}
,"contains":{"row":1}
,"row":{"message":1}
,"times":{"attempts":1}
,"original":{"message":1,"interface":1}
,"full":{"text":1}
,"transformed":{"message":1,"target":1}
,"may":{"present":1}
,"present":{"messages":1}
,"depending":{"nature":1}
,"nature":{"error":1}
,"caused":{"failure":1}
}
;Search.control.loadWordPairs(pairs);
