var pairs =
{
"2023":{"commure":1}
,"material":{"contains":1}
,"contains":{"confidential":1}
,"confidential":{"information":1}
,"information":{"trade":1,"document":1}
,"trade":{"secrets":1}
,"secrets":{"commure":1}
,"commure":{"commure":1,"part":1,"uses":1,"made":1,"products":1,"affiliates":1}
,"part":{"may":1}
,"may":{"reproduced":1,"exist":1}
,"reproduced":{"transmitted":1}
,"transmitted":{"form":1}
,"form":{"means":1}
,"means":{"retained":1}
,"retained":{"storage":1}
,"storage":{"retrieval":1}
,"retrieval":{"system":1}
,"system":{"without":1}
,"without":{"express":1,"prior":1}
,"express":{"written":1}
,"written":{"permission":1}
,"permission":{"commure":1}
,"disclaimer":{"limitation":1}
,"limitation":{"liability":1}
,"uses":{"commercially":1}
,"commercially":{"reasonable":1}
,"reasonable":{"efforts":1}
,"efforts":{"ensure":1,"intended":1}
,"ensure":{"information":1}
,"document":{"accurate":1,"subject":1}
,"accurate":{"publication":1}
,"publication":{"date":1}
,"date":{"commure":1}
,"made":{"efforts":1}
,"intended":{"avoid":1}
,"avoid":{"errors":1}
,"errors":{"may":1}
,"exist":{"information":1}
,"subject":{"change":1}
,"change":{"without":1}
,"prior":{"notice":1}
,"notice":{"construed":1}
,"construed":{"offer":1}
,"offer":{"commitment":1}
,"commitment":{"commure":1}
,"products":{"referenced":1}
,"referenced":{"herein":1}
,"herein":{"either":1,"property":1}
,"either":{"service":1}
,"service":{"marks":1}
,"marks":{"registered":1}
,"registered":{"trademarks":1}
,"trademarks":{"commure":1,"referenced":1}
,"affiliates":{"trademarks":1}
,"property":{"respective":1}
,"respective":{"owners":1}
}
;Search.control.loadWordPairs(pairs);
