var pairs =
{
"viewing":{"errors":1,"error":1}
,"select":{"error":1}
,"error":{"summary":1,"mark":1,"text":1,"listed":1,"limited":1,"category":1,"error":1,"descriptions":1,"categories":1,"statuses":1,"unresolved":1,"viewing":1,"details":1}
,"summary":{"option":1,"groups":1,"sorted":1}
,"option":{"sidebar":1}
,"sidebar":{"left":1}
,"left":{"view":1}
,"view":{"quick":1}
,"quick":{"synopsis":1}
,"synopsis":{"interface":1}
,"interface":{"errors":1,"messages":1}
,"errors":{"currently":1,"error":1,"displayed":1,"listed":1,"want":1}
,"currently":{"unresolved":1}
,"unresolved":{"report":1,"count":1}
,"report":{"meant":1,"includes":1,"apply":1,"down":1}
,"meant":{"used":1}
,"used":{"work":1}
,"work":{"list":1}
,"list":{"active":1,"error":1,"various":1}
,"active":{"issues":1}
,"issues":{"need":1}
,"need":{"addressed":1}
,"addressed":{"resolve":1}
,"resolve":{"error":1}
,"mark":{"ignored":1}
,"ignored":{"removed":1}
,"removed":{"report":1}
,"groups":{"together":1}
,"together":{"errors":1}
,"text":{"error":1,"describing":1,"column":1}
,"listed":{"individual":1,"top":1}
,"individual":{"row":1}
,"row":{"report":1}
,"includes":{"following":1}
,"following":{"information":1}
,"describing":{"error":1}
,"limited":{"detail":1}
,"source":{"system":1}
,"system":{"message":1}
,"message":{"originated":1,"sent":1}
,"target":{"system":1}
,"sent":{"intended":1}
,"intended":{"sent":1}
,"category":{"error":1}
,"descriptions":{"list":1,"complete":1}
,"severity":{"error":1,"levels":1}
,"statuses":{"severity":1}
,"levels":{"definitions":1}
,"definitions":{"severity":1}
,"count":{"number":1}
,"number":{"interface":1}
,"messages":{"error":1}
,"complete":{"list":1}
,"various":{"errors":1}
,"displayed":{"option":1}
,"sorted":{"reverse":1}
,"reverse":{"chronological":1}
,"chronological":{"order":1}
,"order":{"recent":1}
,"recent":{"errors":1}
,"top":{"report":1}
,"apply":{"filter":1}
,"filter":{"filter":1,"narrow":1}
,"narrow":{"report":1}
,"down":{"particular":1}
,"particular":{"subset":1}
,"subset":{"errors":1}
,"want":{"investigate":1}
,"investigate":{"filtering":1}
,"filtering":{"data":1}
,"data":{"screen":1}
,"click":{"link":1}
,"link":{"error":1}
,"column":{"details":1}
,"details":{"error":1}
}
;Search.control.loadWordPairs(pairs);
