var pairs =
{
"data":{"management":1,"integrations":1,"available":1,"data":1}
,"management":{"application":1}
,"application":{"helps":1,"analysts":1,"used":1}
,"helps":{"application":1}
,"analysts":{"integration":1}
,"integration":{"engineers":1}
,"engineers":{"monitor":1}
,"monitor":{"data":1,"interfaces":1}
,"integrations":{"systems":1,"team":1}
,"systems":{"investigate":1,"tracking":1,"integrations":1}
,"investigate":{"resolve":1}
,"resolve":{"errors":1}
,"errors":{"occur":1}
,"occur":{"during":1}
,"during":{"processing":1,"synchronization":1}
,"processing":{"interface":1}
,"interface":{"messages":1,"synchronize":1}
,"messages":{"example":1}
,"example":{"organization":1}
,"organization":{"two":1}
,"two":{"different":1}
,"different":{"systems":1}
,"tracking":{"radiology":1}
,"radiology":{"results":1,"data":1}
,"results":{"order":1}
,"order":{"radiology":1}
,"available":{"systems":1}
,"team":{"configure":1}
,"configure":{"two-way":1}
,"two-way":{"interface":1}
,"synchronize":{"data":1}
,"used":{"monitor":1}
,"interfaces":{"resolve":1}
,"synchronization":{"process":1}
}
;Search.control.loadWordPairs(pairs);
