var pairs =
{
"changing":{"table\u2019s":1}
,"table\u2019s":{"column":1}
,"column":{"order":1,"want":1,"moved":1}
,"order":{"left":1,"columns":1,"pinning":1}
,"left":{"right":1,"far":1,"pin":1}
,"screens":{"table":1}
,"table":{"format":1,"standard":1,"ordered":1,"reverts":1}
,"format":{"display":1}
,"display":{"data":1}
,"data":{"every":1}
,"every":{"table":1}
,"standard":{"order":1}
,"columns":{"listed":1,"either":1,"table":1,"left":1}
,"listed":{"left":1}
,"right":{"change":1,"result":1,"edge":1,"option":1,"side":1}
,"change":{"order":1}
,"pinning":{"columns":1}
,"either":{"far":1}
,"far":{"left":1,"right":1}
,"ordered":{"follows":1}
,"follows":{"default":1}
,"error":{"text":1,"category":1}
,"pin":{"source":1,"error":1,"column":1,"left":1,"right":1}
,"source":{"target":1}
,"target":{"left":1}
,"text":{"right":1}
,"identify":{"column":1}
,"want":{"move":1,"column":1,"unpin":1}
,"move":{"left":1,"additional":1}
,"edge":{"hover":1}
,"hover":{"mouse":1}
,"mouse":{"cursor":1}
,"cursor":{"column\u2019s":1}
,"column\u2019s":{"heading":1}
,"heading":{"expose":1}
,"expose":{"icon":1}
,"icon":{"click":1}
,"context":{"menu":1}
,"menu":{"opens":1}
,"opens":{"list":1}
,"list":{"options":1}
,"choose":{"pin":1,"unpin":1}
,"option":{"depending":1}
,"depending":{"want":1}
,"moved":{"far":1,"back":1}
,"side":{"table":1}
,"optional":{"repeat":1}
,"repeat":{"step":1}
,"step":{"step":1,"times":1}
,"times":{"desired":1}
,"desired":{"move":1}
,"additional":{"columns":1}
,"unpin":{"column":1,"hover":1,"option":1}
,"back":{"original":1}
,"original":{"position":1}
,"position":{"table":1}
,"addition":{"once":1}
,"once":{"log":1}
,"log":{"table":1}
,"reverts":{"default":1}
,"default":{"column":1}
}
;Search.control.loadWordPairs(pairs);
