var pairs =
{
"applying":{"filters":1}
,"click":{"filters":1,"add":1,"apply":1,"clear":1}
,"filters":{"button":1,"applied":1}
,"button":{"located":1}
,"located":{"bottom":1}
,"bottom":{"left":1}
,"left":{"screen":1}
,"screen":{"open":1,"filtered":1}
,"open":{"filter":1}
,"filter":{"option":1}
,"select":{"first":1}
,"first":{"criteria":1}
,"criteria":{"selecting":1,"sure":1,"multiple":1}
,"selecting":{"column":1}
,"column":{"operator":1,"patient":1}
,"operator":{"value":1,"contains":1,"correctly":1}
,"patient":{"mrn":1}
,"value":{"m0001234":1,"field":1}
,"note":{"text":1}
,"text":{"enter":1}
,"enter":{"value":1}
,"field":{"applied":1}
,"applied":{"case":1,"click":1}
,"case":{"sensitive":1}
,"sensitive":{"manner":1}
,"manner":{"example":1}
,"example":{"patient":1}
,"mrn":{"contains":1}
,"contains":{"m0001234":1}
,"m0001234":{"return":1}
,"return":{"different":1}
,"different":{"results":1}
,"results":{"patient":1}
,"add":{"delete":1,"remove":1}
,"delete":{"add":1}
,"remove":{"additional":1}
,"additional":{"criteria":1}
,"sure":{"operator":1}
,"correctly":{"describes":1}
,"describes":{"desired":1}
,"desired":{"relationship":1}
,"relationship":{"criteria":1}
,"multiple":{"operators":1}
,"operators":{"ands":1}
,"ands":{"ors":1}
,"data":{"screen":1}
,"filtered":{"based":1}
,"based":{"criteria":1}
,"clear":{"filters":1}
}
;Search.control.loadWordPairs(pairs);
