var pairs =
{
"editing":{"code":1}
,"code":{"via":1,"either":1,"description":1,"want":1,"drawer":1,"follows":1,"enter":1}
,"via":{"codes":1}
,"codes":{"option":1,"sidebar":1,"using":1}
,"want":{"edit":1}
,"edit":{"code":1,"either":1,"icon":1}
,"either":{"code":1,"scrolling":1}
,"description":{"incorrect":1,"enter":1,"code":1}
,"select":{"codes":1}
,"sidebar":{"left":1}
,"find":{"code":1}
,"scrolling":{"list":1}
,"list":{"codes":1}
,"using":{"filters":1}
,"filters":{"option":1}
,"option":{"search":1}
,"search":{"filtering":1}
,"filtering":{"data":1}
,"data":{"screen":1}
,"click":{"edit":1,"save":1}
,"icon":{"far":1}
,"far":{"left":1}
,"left":{"column":1}
,"drawer":{"right":1}
,"right":{"modify":1}
,"modify":{"fields":1}
,"fields":{"code":1}
,"system":{"cannot":1,"code":1}
,"cannot":{"change":1}
,"change":{"system":1}
,"enter":{"correct":1}
,"correct":{"code":1,"description":1}
}
;Search.control.loadWordPairs(pairs);
