var pairs =
{
"viewing":{"error":1,"message":1}
,"error":{"details":1,"summary":1,"want":1,"text":1,"category":1,"error":1,"descriptions":1,"categories":1,"statuses":1,"limited":1,"unresolved":1,"message":1}
,"view":{"details":1,"click":1}
,"details":{"specific":1,"screen":1}
,"specific":{"error":1,"interface":1}
,"select":{"error":1}
,"summary":{"sidebar":1,"displayed":1}
,"sidebar":{"left":1}
,"locate":{"error":1}
,"want":{"view":1}
,"click":{"link":1}
,"link":{"error":1,"message":1}
,"text":{"column":1,"describing":1}
,"screen":{"opens":1,"information":1,"messages":1,"viewing":1}
,"opens":{"displays":1,"message":1}
,"displays":{"information":1}
,"information":{"particular":1,"shown":1,"displayed":1}
,"particular":{"error":1}
,"top":{"screen":1}
,"shown":{"error":1}
,"source":{"system":1}
,"system":{"message":1}
,"message":{"originated":1,"sent":1,"error":1,"listed":1,"following":1,"message":1,"click":1,"column":1,"opens":1,"details":1}
,"target":{"system":1}
,"sent":{"intended":1}
,"intended":{"sent":1}
,"category":{"error":1}
,"descriptions":{"list":1}
,"list":{"error":1,"specific":1}
,"severity":{"error":1,"levels":1}
,"statuses":{"severity":1}
,"levels":{"definitions":1}
,"definitions":{"severity":1}
,"describing":{"error":1}
,"limited":{"detail":1}
,"unresolved":{"count":1,"please":1}
,"count":{"number":1}
,"number":{"interface":1}
,"interface":{"messages":1,"message":1}
,"messages":{"error":1,"table":1}
,"bottom":{"screen":1}
,"table":{"contains":1,"several":1}
,"contains":{"list":1}
,"please":{"note":1}
,"note":{"given":1}
,"given":{"interface":1}
,"listed":{"messages":1}
,"several":{"different":1}
,"different":{"errors":1}
,"errors":{"message":1}
,"following":{"information":1}
,"column":{"view":1}
,"received":{"date":1}
,"date":{"time":1}
,"time":{"message":1}
,"patient":{"name":1,"mrn":1}
,"name":{"message":1}
,"mrn":{"message":1}
}
;Search.control.loadWordPairs(pairs);
