var pairs =
{
"moving":{"options":1}
,"viewing":{"option":1}
,"option":{"usually":1,"click":1,"open":1,"sidebar":1}
,"usually":{"links":1}
,"links":{"click":1,"located":1}
,"click":{"view":1,"link":1,"breadcrumb":1,"back":1}
,"view":{"detailed":1,"message":1}
,"detailed":{"information":1}
,"information":{"particular":1}
,"particular":{"item":1}
,"item":{"displayed":1}
,"displayed":{"current":1}
,"current":{"screen":1}
,"screen":{"example":1,"following":1,"messages":1}
,"example":{"messages":1,"click":1}
,"messages":{"option":1,"example":1}
,"link":{"view":1}
,"message":{"details":1,"once":1}
,"details":{"specific":1}
,"specific":{"message":1}
,"once":{"drilled":1}
,"drilled":{"down":1}
,"down":{"detail":1}
,"detail":{"screen":1}
,"back":{"previous":1,"button":1}
,"previous":{"screen":1}
,"breadcrumb":{"links":1}
,"located":{"top":1}
,"top":{"page":1}
,"page":{"click":1}
,"button":{"browser":1}
,"different":{"option":1}
,"open":{"sidebar":1}
,"sidebar":{"select":1}
,"select":{"desired":1}
,"desired":{"option":1}
}
;Search.control.loadWordPairs(pairs);
