var pairs =
{
"managing":{"codes":1}
,"map":{"codes":1}
,"codes":{"source":1,"themselves":1,"app":1,"option":1,"used":1,"system":1}
,"source":{"system":1,"code":1}
,"system":{"target":1,"codes":1,"mapping":1}
,"target":{"system":1,"code":1}
,"themselves":{"exist":1}
,"exist":{"data":1}
,"data":{"management":1}
,"management":{"application":1}
,"application":{"create":1}
,"create":{"new":1}
,"new":{"codes":1,"code":1}
,"app":{"using":1}
,"using":{"either":1}
,"either":{"codes":1}
,"option":{"system":1,"differences":1,"quickly":1,"specify":1}
,"mapping":{"option":1,"once":1,"resolve":1,"adding":1}
,"differences":{"two":1}
,"two":{"options":1}
,"during":{"initial":1}
,"initial":{"implementation":1}
,"implementation":{"codes":1,"occasionally":1}
,"quickly":{"add":1}
,"add":{"codes":1,"new":1,"single":1}
,"used":{"particular":1}
,"particular":{"system":1}
,"once":{"added":1}
,"added":{"codes":1}
,"specify":{"source":1}
,"code":{"maps":1,"adding":1,"via":1,"mapping":1,"equivalency":1,"add":1,"fly":1}
,"maps":{"target":1}
,"adding":{"new":1,"code":1}
,"via":{"codes":1}
,"occasionally":{"need":1}
,"need":{"add":1}
,"resolve":{"code":1}
,"equivalency":{"error":1}
,"error":{"require":1}
,"require":{"adding":1}
,"single":{"new":1}
,"fly":{"process":1}
,"process":{"adding":1}
}
;Search.control.loadWordPairs(pairs);
