var pairs =
{
"adding":{"new":1}
,"new":{"code":1,"codes":1}
,"code":{"via":1,"drawer":1,"follows":1,"resides":1,"exist":1,"enter":1}
,"via":{"codes":1}
,"codes":{"option":1,"via":1,"sidebar":1}
,"quickly":{"add":1}
,"add":{"new":1}
,"select":{"codes":1,"system":1}
,"sidebar":{"left":1}
,"click":{"create":1,"save":1}
,"create":{"located":1,"code":1}
,"located":{"top":1}
,"top":{"right":1}
,"right":{"corner":1,"complete":1}
,"corner":{"screen":1}
,"drawer":{"right":1}
,"complete":{"fields":1}
,"fields":{"new":1}
,"system":{"select":1,"code":1}
,"resides":{"example":1}
,"example":{"code":1}
,"exist":{"source":1}
,"source":{"system":1}
,"enter":{"code":1,"description":1}
,"description":{"enter":1,"code":1}
}
;Search.control.loadWordPairs(pairs);
