var pairs =
{
"viewing":{"messages":1,"message":1}
,"select":{"messages":1}
,"messages":{"option":1,"including":1,"processed":1,"listed":1}
,"option":{"sidebar":1,"investigate":1,"contains":1}
,"sidebar":{"left":1}
,"left":{"view":1}
,"view":{"list":1}
,"list":{"interface":1}
,"interface":{"messages":1,"time":1,"message":1}
,"including":{"without":1}
,"without":{"errors":1}
,"errors":{"option":1}
,"investigate":{"issue":1,"filtering":1}
,"issue":{"reported":1}
,"reported":{"interface":1}
,"processed":{"particular":1}
,"particular":{"patient":1}
,"patient":{"interface":1,"name":1,"mrn":1}
,"time":{"frame":1,"message":1}
,"frame":{"report":1}
,"report":{"sorted":1}
,"sorted":{"reverse":1}
,"reverse":{"chronological":1}
,"chronological":{"order":1}
,"order":{"recent":1}
,"recent":{"messages":1}
,"listed":{"top":1}
,"top":{"apply":1}
,"apply":{"filters":1}
,"filters":{"filter":1}
,"filter":{"find":1}
,"find":{"specific":1}
,"specific":{"message":1}
,"message":{"want":1,"displays":1,"message":1,"click":1,"column":1,"viewing":1,"details":1,"originated":1,"sent":1,"statuses":1}
,"want":{"investigate":1}
,"filtering":{"data":1}
,"data":{"screen":1}
,"contains":{"single":1}
,"single":{"row":1}
,"row":{"interface":1}
,"displays":{"following":1}
,"following":{"information":1}
,"information":{"message":1}
,"click":{"link":1}
,"link":{"message":1}
,"column":{"details":1}
,"details":{"message":1}
,"source":{"system":1}
,"system":{"message":1}
,"target":{"system":1}
,"sent":{"intended":1}
,"intended":{"sent":1}
,"status":{"message":1}
,"statuses":{"definitions":1}
,"definitions":{"statuses":1}
,"received":{"date":1}
,"date":{"time":1}
,"name":{"message":1}
,"mrn":{"message":1}
}
;Search.control.loadWordPairs(pairs);
