var pairs =
{
"adding":{"system":1}
,"system":{"mapping":1,"select":1,"interface":1,"system":1}
,"select":{"system":1,"source":1,"target":1}
,"mapping":{"sidebar":1,"drawer":1,"example":1,"meant":1,"radiology":1}
,"sidebar":{"left":1}
,"click":{"create":1,"save":1}
,"create":{"located":1,"system":1}
,"located":{"top":1}
,"top":{"right":1}
,"right":{"corner":1,"enter":1}
,"corner":{"screen":1}
,"drawer":{"right":1}
,"enter":{"following":1,"short":1,"rad":1,"full":1}
,"following":{"information":1}
,"name":{"enter":1,"system":1}
,"short":{"descriptive":1}
,"descriptive":{"name":1}
,"example":{"enter":1,"radiology":1,"mapping":1}
,"rad":{"test":1}
,"test":{"codes-system":1,"codes":1}
,"codes-system":{"system":1}
,"source":{"system":1}
,"interface":{"messages":1}
,"messages":{"derived":1,"sent":1}
,"derived":{"example":1}
,"radiology":{"system":1,"test":1}
,"target":{"system":1}
,"sent":{"example":1}
,"description":{"enter":1,"system":1}
,"full":{"length":1}
,"length":{"description":1}
,"meant":{"represent":1}
,"represent":{"example":1}
,"codes":{"system":1}
}
;Search.control.loadWordPairs(pairs);
