var pairs =
{
"error":{"statuses":1,"status":1,"summary":1,"currently":1,"safely":1,"severity":1,"displayed":1,"severe":1,"due":1,"stopped":1}
,"statuses":{"severity":1}
,"severity":{"levels":1,"level":1,"failure":1,"warning":1,"critical":1}
,"interface":{"message":1,"move":1,"processing":1}
,"message":{"errors":1,"details":1,"fail":1,"severity":1,"successfully":1,"status":1,"processed":1}
,"errors":{"error":1,"table":1,"status":1,"ignored":1,"message":1}
,"status":{"associated":1,"displayed":1,"active":1,"ignored":1,"success":1,"failed":1}
,"associated":{"described":1}
,"described":{"below":1}
,"below":{"error\u2019s":1,"severity":1}
,"error\u2019s":{"status":1}
,"displayed":{"errors":1,"error":1}
,"table":{"message":1}
,"details":{"screen":1,"show":1}
,"screen":{"important":1}
,"important":{"note":1}
,"note":{"errors":1}
,"active":{"aggregated":1,"error":1,"unresolved":1}
,"aggregated":{"displayed":1}
,"currently":{"active":1}
,"ignored":{"user":1,"indicated":1,"data":1}
,"user":{"determined":1}
,"determined":{"error":1}
,"safely":{"ignored":1}
,"indicated":{"changing":1}
,"changing":{"status":1}
,"data":{"management":1}
,"management":{"application":1}
,"application":{"marking":1}
,"marking":{"errors":1}
,"level":{"associated":1,"error":1}
,"summary":{"errors":1}
,"warning":{"error":1}
,"severe":{"enough":1}
,"enough":{"cause":1,"stopped":1}
,"cause":{"message":1}
,"fail":{"processing":1}
,"processing":{"long":1,"message":1,"messages":1}
,"long":{"errors":1}
,"failure":{"message":1,"error":1,"although":1}
,"successfully":{"processed":1}
,"processed":{"message":1,"interface":1}
,"show":{"message":1,"interface":1}
,"success":{"error":1}
,"due":{"missing":1,"incorrect":1}
,"missing":{"code":1}
,"code":{"mapping":1}
,"mapping":{"non-required":1,"required":1}
,"non-required":{"field":1}
,"field":{"severity":1}
,"failed":{"error":1}
,"although":{"specific":1}
,"specific":{"message":1}
,"move":{"next":1}
,"next":{"message":1}
,"required":{"field":1}
,"critical":{"error":1}
,"stopped":{"interface":1}
,"incorrect":{"address":1}
,"address":{"destination":1}
,"destination":{"system":1}
,"system":{"severity":1}
,"undefined":{"unknown":1}
,"unknown":{"edge":1}
,"edge":{"case":1}
,"case":{"error":1}
,"messages":{"require":1}
,"require":{"intervention":1}
,"intervention":{"commure":1}
,"commure":{"support":1}
}
;Search.control.loadWordPairs(pairs);
