var pairs =
{
"resolving":{"code":1}
,"code":{"equivalency":1,"source":1,"target":1,"lookup":1,"mapping":1,"correct":1,"adding":1,"editing":1}
,"equivalency":{"issues":1,"error":1,"problem":1}
,"source":{"system":1,"code":1,"target":1}
,"system":{"mapped":1,"error":1,"type":1,"match":1}
,"mapped":{"code":1,"wrong":1}
,"target":{"system":1,"code":1}
,"error":{"occur":1,"display":1,"summary":1,"reprocessing":1,"data":1}
,"occur":{"during":1}
,"during":{"interface":1}
,"interface":{"processing":1,"messages":1}
,"processing":{"code":1}
,"lookup":{"match":1}
,"match":{"error":1,"display":1}
,"display":{"error":1}
,"summary":{"errors":1}
,"errors":{"resolved":1}
,"resolved":{"directly":1,"using":1}
,"directly":{"data":1}
,"data":{"management":1,"source":1,"overwrite":1,"example":1}
,"management":{"application":1}
,"application":{"using":1,"resolved":1}
,"using":{"following":1}
,"following":{"process":1}
,"add":{"new":1}
,"new":{"code":1}
,"mapping":{"map":1,"source":1,"reprocess":1}
,"map":{"source":1}
,"correct":{"target":1}
,"adding":{"code":1}
,"reprocess":{"interface":1,"reprocessing":1,"message":1}
,"messages":{"code":1,"option":1,"used":1}
,"reprocessing":{"interface":1,"runs":1}
,"common":{"code":1}
,"problem":{"code":1}
,"wrong":{"code":1}
,"type":{"issue":1}
,"issue":{"identified":1}
,"identified":{"user":1}
,"user":{"notices":1}
,"notices":{"patient":1}
,"patient":{"data":1}
,"change":{"mapping":1}
,"editing":{"deleting":1}
,"deleting":{"code":1}
,"option":{"search":1}
,"search":{"interface":1}
,"used":{"incorrect":1}
,"incorrect":{"mapping":1}
,"caution":{"please":1}
,"please":{"care":1}
,"care":{"determining":1}
,"determining":{"whether":1}
,"whether":{"reprocess":1}
,"message":{"reprocessing":1,"containing":1,"final":1,"preliminary":1}
,"runs":{"risk":1}
,"risk":{"sending":1}
,"sending":{"older":1}
,"older":{"version":1}
,"version":{"data":1}
,"overwrite":{"newer":1}
,"newer":{"version":1}
,"example":{"let\u2019s":1}
,"let\u2019s":{"assume":1}
,"assume":{"message":1}
,"containing":{"preliminary":1}
,"preliminary":{"radiology":1,"result":1}
,"radiology":{"result":1}
,"result":{"failed":1,"successful":1,"preliminary":1,"replace":1,"target":1}
,"failed":{"later":1}
,"later":{"different":1}
,"different":{"message":1}
,"final":{"results":1,"result":1}
,"results":{"radiology":1}
,"successful":{"reprocessed":1}
,"reprocessed":{"earlier":1}
,"earlier":{"message":1}
,"replace":{"final":1}
}
;Search.control.loadWordPairs(pairs);
