var pairs =
{
"managing":{"system":1,"codes":1,"code":1}
,"system":{"code":1,"work":1,"typically":1,"img123":1,"different":1,"mapping":1,"mappings":1,"within":1,"equivalent":1,"managing":1}
,"code":{"mappings":1,"sets":1,"exists":1,"target":1,"mapped":1,"item":1}
,"order":{"interface":1}
,"interface":{"system":1,"cases":1,"create":1}
,"work":{"code":1}
,"sets":{"used":1,"items":1,"managing":1}
,"used":{"two":1}
,"two":{"systems":1}
,"systems":{"mapped":1,"code":1}
,"mapped":{"example":1,"whatever":1,"even":1}
,"example":{"interfacing":1,"test":1}
,"interfacing":{"radiology":1}
,"radiology":{"data":1}
,"data":{"system":1}
,"typically":{"system":1}
,"items":{"tests":1}
,"tests":{"results":1}
,"results":{"facilities":1}
,"facilities":{"means":1}
,"means":{"example":1}
,"test":{"code":1}
,"exists":{"source":1}
,"source":{"system":1,"target":1}
,"img123":{"represents":1}
,"represents":{"x-ray":1}
,"x-ray":{"mandible":1}
,"mandible":{"mapped":1}
,"whatever":{"equivalent":1}
,"equivalent":{"code":1,"codes":1}
,"target":{"system":1,"systems":1}
,"depending":{"specifications":1}
,"specifications":{"interface":1}
,"cases":{"codes":1,"may":1}
,"codes":{"code":1,"source":1,"require":1,"target":1}
,"even":{"source":1}
,"item":{"cases":1}
,"may":{"required":1}
,"required":{"map":1}
,"map":{"codes":1}
,"different":{"code":1}
,"steps":{"configure":1}
,"configure":{"system":1}
,"mappings":{"follows":1}
,"create":{"system":1,"codes":1}
,"mapping":{"necessary":1,"managing":1,"map":1}
,"necessary":{"code":1}
,"within":{"interface":1}
,"require":{"mapping":1}
}
;Search.control.loadWordPairs(pairs);
