var pairs =
{
"resolving":{"errors":1,"issue":1}
,"reviewing":{"errors":1}
,"errors":{"error":1,"ignored":1,"displayed":1}
,"error":{"summary":1,"issue":1,"ignored":1,"due":1,"descriptions":1}
,"summary":{"messages":1,"report":1}
,"messages":{"options":1}
,"options":{"determine":1}
,"determine":{"course":1}
,"course":{"action":1}
,"issue":{"resolved":1,"want":1,"code":1}
,"resolved":{"making":1}
,"making":{"change":1}
,"change":{"sending":1}
,"sending":{"receiving":1}
,"receiving":{"system":1}
,"system":{"via":1}
,"via":{"action":1}
,"action":{"taken":1}
,"taken":{"outside":1}
,"outside":{"data":1}
,"data":{"management":1}
,"management":{"application":1}
,"application":{"case":1}
,"case":{"resolving":1}
,"want":{"indicate":1}
,"indicate":{"error":1}
,"ignored":{"fall":1}
,"fall":{"error":1}
,"report":{"marking":1}
,"marking":{"errors":1}
,"due":{"issue":1}
,"code":{"equivalencies":1,"mapping":1}
,"equivalencies":{"need":1}
,"need":{"create":1}
,"create":{"edit":1}
,"edit":{"delete":1}
,"delete":{"code":1}
,"mapping":{"adding":1,"editing":1}
,"adding":{"code":1}
,"editing":{"deleting":1}
,"deleting":{"code":1}
,"descriptions":{"complete":1}
,"complete":{"list":1}
,"list":{"various":1}
,"various":{"errors":1}
,"displayed":{"data":1}
}
;Search.control.loadWordPairs(pairs);
