var pairs =
{
"editing":{"system":1}
,"system":{"mapping":1}
,"made":{"mistake":1}
,"mistake":{"adding":1}
,"adding":{"system":1}
,"mapping":{"want":1,"follow":1,"sidebar":1,"drawer":1}
,"want":{"edit":1}
,"edit":{"name":1,"click":1,"icon":1,"system":1}
,"name":{"description":1}
,"description":{"system":1}
,"follow":{"steps":1}
,"select":{"system":1}
,"sidebar":{"left":1}
,"identify":{"system":1}
,"click":{"edit":1,"save":1}
,"icon":{"far":1}
,"far":{"left":1}
,"left":{"column":1}
,"drawer":{"right":1}
,"right":{"necessary":1}
,"necessary":{"changes":1}
,"changes":{"fields":1}
,"fields":{"described":1}
,"described":{"step":1}
,"step":{"adding":1}
}
;Search.control.loadWordPairs(pairs);
