var pairs =
{
"message":{"statuses":1,"details":1,"status":1,"currently":1,"processed":1,"reprocessed":1,"chose":1,"received":1,"starts":1}
,"interface":{"message":1,"messages":1,"criteria":1}
,"statuses":{"below":1,"illustrated":1}
,"below":{"message\u2019s":1}
,"message\u2019s":{"status":1}
,"status":{"displayed":1,"least":1,"errors":1,"queued":1}
,"displayed":{"messages":1}
,"messages":{"option":1,"transitory":1,"specific":1}
,"option":{"message":1}
,"details":{"screen":1}
,"currently":{"waiting":1}
,"waiting":{"processed":1}
,"processed":{"transitory":1,"due":1,"successfully":1,"match":1}
,"transitory":{"state":1}
,"due":{"errors":1}
,"errors":{"message":1,"severity":1}
,"least":{"error":1}
,"error":{"severity":1}
,"severity":{"failure":1,"warning":1}
,"failure":{"possibly":1,"errors":1}
,"possibly":{"additional":1}
,"additional":{"errors":1}
,"successfully":{"message":1}
,"warning":{"error":1,"prevent":1}
,"prevent":{"message":1}
,"reprocessed":{"user":1}
,"user":{"addressed":1}
,"addressed":{"errors":1}
,"chose":{"reprocess":1}
,"reprocess":{"reprocessing":1}
,"reprocessing":{"interface":1}
,"received":{"cannot":1}
,"cannot":{"processed":1}
,"match":{"specific":1}
,"specific":{"filter":1,"facility":1,"type":1}
,"filter":{"criteria":1,"messages":1}
,"criteria":{"continue":1,"may":1}
,"continue":{"processing":1}
,"processing":{"example":1}
,"example":{"interface":1}
,"may":{"filter":1}
,"facility":{"messages":1}
,"starts":{"status":1}
,"queued":{"travels":1}
,"travels":{"statuses":1}
,"illustrated":{"below":1}
}
;Search.control.loadWordPairs(pairs);
