var pairs =
{
"reviewing":{"messages":1}
,"messages":{"errors":1,"option":1,"view":1,"error":1,"currently":1}
,"data":{"management":1}
,"management":{"application":1}
,"application":{"provides":1}
,"provides":{"views":1}
,"views":{"two":1}
,"two":{"types":1,"errors":1}
,"types":{"integration":1}
,"integration":{"information":1}
,"information":{"interface":1}
,"interface":{"messages":1,"messages.this":1,"message":1}
,"option":{"displays":1,"drill":1,"clicked":1,"error":1}
,"displays":{"list":1,"total":1}
,"list":{"interface":1,"errors":1}
,"drill":{"down":1}
,"down":{"details":1}
,"details":{"individual":1,"given":1,"errors":1,"screen":1,"message":1}
,"individual":{"messages":1}
,"view":{"errors":1,"specific":1,"details":1}
,"errors":{"occurred":1,"error":1,"matching":1,"listed":1}
,"occurred":{"particular":1,"during":1}
,"particular":{"message":1}
,"message":{"viewing":1,"error":1,"x1234":1,"x12345":1,"details":1}
,"viewing":{"messages":1,"errors":1}
,"error":{"summary":1,"text":1,"option":1,"view":1,"viewing":1,"therefore":1,"listed":1,"matching":1,"details":1,"clicked":1}
,"summary":{"option":1}
,"during":{"processing":1}
,"processing":{"interface":1}
,"messages.this":{"report":1}
,"report":{"groups":1}
,"groups":{"together":1}
,"together":{"active":1}
,"active":{"errors":1}
,"text":{"displays":1}
,"total":{"number":1}
,"number":{"messages":1}
,"given":{"error":1,"interface":1}
,"specific":{"interface":1}
,"currently":{"error":1}
,"therefore":{"listed":1}
,"listed":{"multiple":1,"message":1,"separate":1,"error":1}
,"multiple":{"errors":1}
,"x1234":{"two":1}
,"matching":{"code":1}
,"code":{"img55":1,"abn12":1}
,"img55":{"matching":1,"view":1}
,"clicked":{"message":1,"first":1,"second":1}
,"x12345":{"view":1,"listed":1}
,"separate":{"row":1}
,"row":{"screen":1}
,"screen":{"clicked":1,"along":1}
,"first":{"error":1}
,"along":{"interface":1,"messages":1}
,"second":{"error":1}
,"abn12":{"view":1}
}
;Search.control.loadWordPairs(pairs);
