var pairs =
{
"managing":{"code":1}
,"code":{"mappings":1,"enter":1,"img123":1,"gmandible":1,"radiology":1,"mapping":1,"mapped":1}
,"once":{"created":1}
,"created":{"system":1}
,"system":{"mapping":1,"mapped":1,"several":1,"map":1,"many-to-one":1}
,"mapping":{"code":1,"entries":1}
,"enter":{"mappings":1}
,"mappings":{"actual":1}
,"actual":{"codes":1}
,"codes":{"code":1,"radiology":1}
,"specify":{"test":1}
,"test":{"code":1}
,"img123":{"radiology":1,"gmandible":1}
,"radiology":{"system":1}
,"mapped":{"test":1,"incorrectly":1}
,"gmandible":{"radiology":1,"img456":1}
,"several":{"codes":1}
,"map":{"code":1}
,"many-to-one":{"relationship":1}
,"relationship":{"create":1}
,"create":{"multiple":1}
,"multiple":{"mapping":1}
,"entries":{"example":1}
,"example":{"map":1}
,"img456":{"gmandible":1}
,"edit":{"delete":1}
,"delete":{"code":1}
}
;Search.control.loadWordPairs(pairs);
