var pairs =
{
"changing":{"sort":1}
,"sort":{"order":1,"different":1,"table":1,"asc":1,"desc":1}
,"order":{"table":1,"indicated":1,"column\u2019s":1,"clicking":1,"selected":1}
,"screens":{"table":1}
,"table":{"format":1,"sort":1,"sorted":1,"toggle":1,"reverts":1}
,"format":{"display":1}
,"display":{"data":1}
,"data":{"tables":1,"using":1}
,"tables":{"default":1}
,"default":{"sort":1}
,"indicated":{"arrow":1}
,"arrow":{"down":1,"column":1,"means":1,"appears":1}
,"down":{"arrow":1}
,"column":{"headings":1,"ascending":1,"used":1,"order":1}
,"means":{"report":1}
,"report":{"sorted":1}
,"sorted":{"ascending":1,"descending":1,"column":1}
,"ascending":{"order":1,"descending":1}
,"column\u2019s":{"data":1,"heading":1}
,"descending":{"order":1}
,"change":{"table":1}
,"different":{"column\u2019s":1}
,"using":{"either":1}
,"either":{"methods":1,"heading":1}
,"methods":{"below":1}
,"click":{"column\u2019s":1}
,"heading":{"name":1,"expose":1}
,"name":{"arrow":1}
,"appears":{"hover":1}
,"hover":{"mouse":1}
,"mouse":{"cursor":1}
,"cursor":{"heading":1,"column\u2019s":1}
,"once":{"column":1,"log":1}
,"used":{"sort":1}
,"toggle":{"ascending":1}
,"clicking":{"repeatedly":1}
,"repeatedly":{"either":1}
,"expose":{"icon":1}
,"icon":{"click":1}
,"context":{"menu":1}
,"menu":{"opens":1}
,"opens":{"list":1}
,"list":{"options":1}
,"choose":{"sort":1}
,"asc":{"sort":1}
,"desc":{"option":1}
,"log":{"table":1}
,"reverts":{"default":1}
}
;Search.control.loadWordPairs(pairs);
