var pairs =
{
"ways":{"help":1}
,"help":{"system":1,"commure":1}
,"system":{"administrator":1}
,"administrator":{"problem":1,"cannot":1}
,"problem":{"running":1}
,"running":{"application":1}
,"application":{"first":1,"you\u2019re":1}
,"first":{"report":1}
,"report":{"issue":1}
,"issue":{"hospital\u0027s":1,"send":1,"possible":1}
,"hospital\u0027s":{"strongline":1}
,"strongline":{"administrator":1}
,"commure":{"support":1}
,"support":{"administrator":1,"respond":1,"available":1}
,"cannot":{"solve":1}
,"solve":{"issue":1}
,"send":{"e-mail":1}
,"e-mail":{"commure_support@commure.com":1,"address":1}
,"commure_support@commure.com":{"include":1}
,"include":{"contact":1,"details":1}
,"contact":{"information":1}
,"information":{"name":1,"error":1}
,"name":{"telephone":1}
,"telephone":{"number":1,"support":1}
,"number":{"e-mail":1,"best":1}
,"address":{"office":1}
,"office":{"cell":1}
,"cell":{"number":1}
,"best":{"time":1}
,"time":{"call":1}
,"call":{"please":1}
,"please":{"include":1}
,"details":{"issue":1}
,"possible":{"application":1}
,"you\u2019re":{"using":1}
,"using":{"whether":1}
,"whether":{"desktop":1}
,"desktop":{"mobile":1}
,"mobile":{"device":1}
,"device":{"user":1,"version":1}
,"user":{"indicate":1}
,"indicate":{"type":1}
,"type":{"device":1}
,"version":{"information":1}
,"error":{"messages":1}
,"messages":{"affected":1}
,"affected":{"commure":1}
,"respond":{"next":1}
,"next":{"business":1}
,"business":{"day":1,"holidays":1}
,"day":{"telephone":1}
,"available":{"8:00":1}
,"8:00":{"8:00":1,"est":1}
,"est":{"monday":1}
,"monday":{"friday":1}
,"friday":{"excluding":1}
,"excluding":{"regular":1}
,"regular":{"business":1}
,"holidays":{"888-994-2443":1}
}
;Search.control.loadWordPairs(pairs);
