var pairs =
{
"modifying":{"deleting":1}
,"deleting":{"filter":1}
,"change":{"criteria":1,"aspect":1}
,"criteria":{"used":1,"adding":1,"changing":1}
,"used":{"filter":1}
,"filter":{"delete":1,"time":1,"drop-down":1,"want":1,"option":1,"filter":1,"set\u2019s":1,"change":1,"changing":1,"click":1}
,"delete":{"filter":1}
,"drop-down":{"select":1}
,"select":{"filter":1}
,"want":{"modify":1}
,"click":{"gears":1,"update":1,"delete":1}
,"gears":{"icon":1}
,"icon":{"located":1}
,"located":{"right":1}
,"right":{"filter":1}
,"option":{"opens":1}
,"opens":{"displaying":1}
,"displaying":{"criteria":1}
,"set\u2019s":{"name":1}
,"either":{"modify":1}
,"modify":{"delete":1,"filter":1}
,"aspect":{"filter":1}
,"changing":{"attributes":1,"operator":1,"name":1}
,"attributes":{"particular":1}
,"particular":{"criteria":1}
,"adding":{"removing":1}
,"removing":{"criteria":1}
,"operator":{"changing":1}
,"name":{"filter":1}
,"update":{"save":1}
,"save":{"changes":1}
}
;Search.control.loadWordPairs(pairs);
