var pairs =
{
"commure":{"applications":1}
,"applications":{"contain":1,"always":1}
,"contain":{"expandable":1}
,"expandable":{"sidebar":1}
,"sidebar":{"left":1,"looks":1,"collapsed":1,"click":1,"show":1,"double-click":1}
,"left":{"side":1,"corner":1}
,"side":{"screen":1}
,"screen":{"organization":1}
,"organization":{"purchased":1,"purchase":1}
,"purchased":{"application":1}
,"application":{"data":1,"sidebar":1,"list":1,"icon":1,"action":1}
,"data":{"management":1}
,"management":{"application":1}
,"looks":{"illustrated":1}
,"illustrated":{"below":1}
,"below":{"sidebar":1}
,"collapsed":{"shows":1}
,"shows":{"nothing":1}
,"nothing":{"expanded":1}
,"expanded":{"displays":1}
,"displays":{"application\u2019s":1}
,"application\u2019s":{"main":1}
,"main":{"options":1}
,"options":{"simply":1,"selected":1}
,"simply":{"open":1}
,"open":{"sidebar":1,"close":1}
,"click":{"option":1,"application":1,"menu":1}
,"option":{"select":1}
,"purchase":{"application":1}
,"list":{"applications":1}
,"always":{"displayed":1}
,"displayed":{"icons":1}
,"icons":{"sidebar":1}
,"icon":{"select":1,"located":1,"again":1}
,"select":{"application":1}
,"action":{"expands":1}
,"expands":{"sidebar":1}
,"show":{"main":1}
,"selected":{"application":1}
,"two":{"additional":1}
,"additional":{"ways":1}
,"ways":{"open":1}
,"close":{"sidebar":1}
,"method":{"click":1,"double-click":1}
,"menu":{"icon":1}
,"located":{"top":1}
,"top":{"left":1}
,"corner":{"app":1}
,"app":{"open":1}
,"again":{"close":1}
,"double-click":{"anywhere":1,"bar":1}
,"anywhere":{"light":1}
,"light":{"blue":1}
,"blue":{"vertical":1}
,"vertical":{"bar":1}
,"bar":{"open":1,"again":1}
}
;Search.control.loadWordPairs(pairs);
