var pairs =
{
"editing":{"deleting":1,"code":1}
,"deleting":{"code":1}
,"code":{"mapping":1,"mapped":1,"target":1,"mappings":1,"enter":1,"used":1,"just":1}
,"determine":{"source":1}
,"source":{"code":1,"system":1}
,"mapped":{"wrong":1}
,"wrong":{"code":1}
,"target":{"system":1,"code":1}
,"system":{"correct":1,"mapping":1,"mappings":1,"source":1}
,"correct":{"editing":1}
,"mapping":{"code":1,"needs":1,"sidebar":1,"want":1,"correction":1,"click":1,"edit":1,"drawer":1,"information":1}
,"needs":{"deleted":1}
,"deleted":{"reason":1}
,"reason":{"delete":1}
,"select":{"system":1,"values":1}
,"sidebar":{"left":1}
,"identify":{"system":1}
,"want":{"code":1,"edit":1}
,"correction":{"click":1}
,"click":{"link":1,"delete":1,"edit":1,"save":1}
,"link":{"name":1}
,"name":{"column":1}
,"mappings":{"details":1,"listed":1,"table":1,"using":1}
,"details":{"screen":1}
,"screen":{"opens":1}
,"opens":{"existing":1,"right":1}
,"existing":{"code":1}
,"listed":{"code":1}
,"table":{"bottom":1}
,"bottom":{"screen":1}
,"find":{"mapping":1}
,"edit":{"delete":1,"code":1,"icon":1}
,"delete":{"either":1,"code":1,"icon":1}
,"either":{"scrolling":1}
,"scrolling":{"list":1}
,"list":{"code":1}
,"using":{"filters":1}
,"filters":{"option":1}
,"option":{"search":1}
,"search":{"filtering":1}
,"filtering":{"data":1}
,"data":{"screen":1}
,"icon":{"next":1}
,"next":{"desired":1}
,"desired":{"code":1}
,"drawer":{"opens":1}
,"right":{"corrections":1}
,"corrections":{"fields":1}
,"fields":{"below":1}
,"below":{"necessary":1}
,"necessary":{"click":1}
,"save":{"step":1}
,"step":{"adding":1}
,"adding":{"code":1}
,"information":{"select":1}
,"values":{"fields":1}
,"enter":{"code":1,"equivalent":1}
,"used":{"source":1}
,"equivalent":{"code":1}
,"just":{"entered":1}
,"entered":{"above":1}
}
;Search.control.loadWordPairs(pairs);
