var pairs =
{
"marking":{"errors":1}
,"errors":{"ignored":1,"row":1}
,"determined":{"error":1}
,"error":{"safely":1,"summary":1,"wish":1,"error":1,"text":1,"details":1,"reviewing":1,"table":1,"located":1,"status":1,"changed":1,"removed":1}
,"safely":{"ignored":1}
,"ignored":{"resolved":1,"removed":1,"click":1,"error":1,"errors":1}
,"resolved":{"outside":1}
,"outside":{"data":1}
,"data":{"management":1}
,"management":{"application":1}
,"application":{"change":1}
,"change":{"status":1}
,"status":{"ignored":1,"error":1}
,"removed":{"error":1}
,"summary":{"report":1,"slide-out":1,"display":1}
,"select":{"error":1}
,"slide-out":{"menu":1}
,"menu":{"drawer":1}
,"identify":{"error":1}
,"wish":{"mark":1}
,"mark":{"ignored":1}
,"click":{"link":1,"ignore":1}
,"link":{"error":1}
,"text":{"column":1}
,"details":{"screen":1,"top":1}
,"screen":{"confirm":1}
,"confirm":{"correct":1}
,"correct":{"error":1}
,"reviewing":{"details":1}
,"top":{"page":1,"right":1}
,"page":{"messages":1}
,"messages":{"error":1,"particular":1,"ignored":1}
,"table":{"bottom":1}
,"bottom":{"page":1}
,"ignore":{"error":1}
,"located":{"top":1}
,"right":{"screen":1}
,"particular":{"error":1}
,"changed":{"ignored":1}
,"display":{"aggregate":1}
,"aggregate":{"messages":1}
,"row":{"particular":1}
}
;Search.control.loadWordPairs(pairs);
