var pairs =
{
"managing":{"system":1}
,"system":{"mappings":1,"system":1,"typically":1,"mapping":1,"create":1}
,"given":{"data":1}
,"data":{"integration":1,"synchronization":1,"management":1}
,"integration":{"system":1,"depends":1,"within":1}
,"mappings":{"option":1,"required":1,"code":1,"typically":1}
,"option":{"specify":1}
,"specify":{"code":1}
,"code":{"sets":1,"used":1}
,"sets":{"need":1}
,"need":{"mapped":1}
,"mapped":{"source":1}
,"source":{"target":1,"system":1}
,"target":{"systems":1,"system":1}
,"systems":{"number":1}
,"number":{"system":1}
,"required":{"data":1}
,"depends":{"type":1}
,"type":{"interface":1}
,"interface":{"designed":1,"system":1,"example":1,"unique":1}
,"designed":{"implemented":1}
,"example":{"one-way":1,"create":1,"two-way":1}
,"one-way":{"interface":1}
,"typically":{"create":1,"one-time":1}
,"create":{"system":1}
,"used":{"interface":1,"interfaces":1}
,"mapping":{"name":1}
,"rad":{"test":1,"result":1}
,"test":{"codes":1}
,"result":{"codes":1}
,"two-way":{"interface":1,"data":1}
,"synchronization":{"interface":1}
,"interfaces":{"going":1}
,"going":{"directions":1}
,"directions":{"example":1}
,"unique":{"may":1}
,"may":{"different":1}
,"different":{"requirements":1}
,"requirements":{"consult":1}
,"consult":{"commure":1}
,"commure":{"representative":1}
,"representative":{"creating":1}
,"creating":{"system":1}
,"one-time":{"set-up":1}
,"set-up":{"performed":1}
,"performed":{"initial":1}
,"initial":{"implementation":1}
,"implementation":{"data":1}
,"within":{"data":1}
,"management":{"application":1}
}
;Search.control.loadWordPairs(pairs);
